url: https://thewhiteh4t.github.io
title: thewhiteh4t's blog
author: thewhiteh4t
email: thewhiteh4t@protonmail.com
layouts_dir: _layouts
paginate: 6
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "default"

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-feed
  - jekyll-postcss

postcss:
  cache: false
